backend:
  name: github
  branch: master
  repo: vogelino/charlottestuby.com
  base_url: 'https://radical-cumbersome-check.glitch.me/'
  auth_endpoint: auth
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'
media_folder: /public/img
public_folder: /img
collections:
  - name: work
    label: Work
    folder: content/work
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - label: Template Key
        name: templateKey
        widget: hidden
        default: work
      - label: Order of appearance
        name: orderOfAppearance
        widget: number
        default: 999
      - label: Title
        name: title
        widget: string
      - label: Sous-titre
        name: subtitle
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Description
        name: description
        widget: text
      - label: Image présentant ton projet
        name: thumbnail
        widget: image
      - label: Forme décorative
        name: decorativeForm
        widget: image
      - label: Gallerie d'images
        name: images
        widget: list
        fields:
          - label: Image
            name: image
            widget: image
          - label: Légende
            name: caption
            widget: string
            required: false
  - name: pages
    label: Pages
    files:
      - file: content/index.md
        label: Landing Page
        name: index
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: index-page
      - file: content/about.md
        label: About
        name: about
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: about-page
          - label: Title
            name: title
            widget: string
          - label: Subtitle
            name: subtitle
            widget: text
          - label: Portrait
            name: portrait
            widget: image
          - label: Contact email
            name: email
            widget: string
            required: false
          - label: Email button text
            name: emailButtonText
            widget: string
            required: false
          - label: Curriculum PDF
            name: cv
            widget: file
            allow_multiple: false
            media_library:
              config:
                multiple: false
            required: false
          - label: CV button text
            name: cvButtonText
            widget: string
            required: false
          - label: Instagram username
            name: instagramUsername
            widget: string
            required: false
          - label: Instagram button text
            name: instagramButtonText
            widget: string
            required: false
          - label: Body
            name: body
            widget: markdown
          - label: Formes
            name: forms
            widget: list
            fields:
              - label: Image
                name: image
                widget: image
                allow_multiple: false
              - label: Left position (in percent)
                name: posX
                widget: number
              - label: Top position (in percent)
                name: posY
                widget: number
      - file: content/press.md
        label: Press Page
        name: press
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: press-page
          - label: Press Links
            name: pressList
            widget: list
            fields:
              - label: Date
                name: date
                widget: date
                format: MMM. YYYY
              - label: Title
                name: title
                widget: string
              - label: Url (If weblink)
                name: url
                widget: string
                pattern:
                  - https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)
                  - Must be a valid url
                required: false
              - label: PDF File
                name: pdfFile
                widget: file
                allow_multiple: false
                media_library:
                  config:
                    multiple: false
                required: false
              - label: Screenshot (Of Webpage or PDF)
                name: screenshot
                widget: image
              - label: Color
                name: color
                widget: string
                pattern:
                  - ^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$
                  - Must be an color string in HEX format (eg. \#BADASS)
      - file: content/stubyAndFischer.md
        label: Stuby & Fischer
        name: stuby-and-fischer
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: stuby-and-fischer-page
          - label: Title
            name: title
            widget: string
          - label: Intro Image
            name: introImage
            widget: image
          - label: Body
            name: body
            widget: markdown
          - label: Intro Button Text
            name: introButtonText
            widget: string
            required: false
          - label: Intro Button Link
            name: introButtonLink
            widget: string
            required: false
          - label: Projects
            name: projects
            widget: list
            fields:
              - label: Project Title
                name: projectTitle
                widget: string
              - label: Project Description
                name: projectDescription
                widget: markdown
              - label: Project Button Text
                name: projectButtonText
                widget: string
                required: false
              - label: Project Button Link
                name: projectButtonLink
                widget: string
                required: false
              - label: Text Start X
                name: textStartX
                widget: number
              - label: Text Start Y
                name: textStartY
                widget: number
              - label: Text End X
                name: textEndX
                widget: number
              - label: Text End Y
                name: textEndY
                widget: number
              - label: Project Images
                name: projetImages
                widget: list
                fields:
                  - label: Project Image
                    name: projectImage
                    widget: image
                  - label: Start X
                    name: startX
                    widget: number
                  - label: Start Y
                    name: startY
                    widget: number
                  - label: End X
                    name: endX
                    widget: number
                  - label: End Y
                    name: endY
                    widget: number

